menu_entity_index.configuration.entity_types:
  type: sequence
  label: 'Tracked entity types'
  sequence:
    type: string
    label: 'Entity type machine name'
menu_entity_index.configuration.menus:
  type: sequence
  label: 'Tracked menus'
  sequence:
    type: string
    label: 'Menu machine name'
